name: flc_rest_api_test
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  prefs_storage:
    path: packages/prefs_storage
  api_client:
    path: packages/api_client
  auth_repo:
    path: packages/auth_repo
  notifications_repo:
    path: packages/notifications_repo  
  get_it: ^9.2.0
  formz: ^0.8.0
  equatable: ^2.0.7
    
  
  
dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
